# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97a74d8d640424f6bbeb09685484d834580bfa5d50fb9e15f5caf6fa2d935ef0e0f09c5a0d228d8dbe619a30116b988cdc60d1e9091c6c4a9b8a1f4eb304806e

test:
  secret_key_base: a0776c21a5cca511aa7f7a882e02c90baae781b708c3262ebd943fdc34a1c33d1b1549a903cd12712b5691c2372117885910c87e35967161614669c5ee1ac7d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
